(function() {var implementors = {};
implementors["adler32"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"adler32/struct.RollingAdler32.html\" title=\"struct adler32::RollingAdler32\">RollingAdler32</a>","synthetic":false,"types":["adler32::RollingAdler32"]}];
implementors["crc32fast"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"crc32fast/struct.Hasher.html\" title=\"struct crc32fast::Hasher\">Hasher</a>","synthetic":false,"types":["crc32fast::Hasher"]}];
implementors["flate2"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"flate2/struct.GzHeader.html\" title=\"struct flate2::GzHeader\">GzHeader</a>","synthetic":false,"types":["flate2::gz::GzHeader"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"flate2/struct.Compression.html\" title=\"struct flate2::Compression\">Compression</a>","synthetic":false,"types":["flate2::Compression"]}];
implementors["miniz_oxide"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"miniz_oxide/deflate/core/struct.CompressorOxide.html\" title=\"struct miniz_oxide::deflate::core::CompressorOxide\">CompressorOxide</a>","synthetic":false,"types":["miniz_oxide::deflate::core::CompressorOxide"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"miniz_oxide/inflate/core/struct.DecompressorOxide.html\" title=\"struct miniz_oxide::inflate::core::DecompressorOxide\">DecompressorOxide</a>","synthetic":false,"types":["miniz_oxide::inflate::core::DecompressorOxide"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"miniz_oxide/inflate/stream/struct.InflateState.html\" title=\"struct miniz_oxide::inflate::stream::InflateState\">InflateState</a>","synthetic":false,"types":["miniz_oxide::inflate::stream::InflateState"]}];
implementors["tar"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"tar/struct.GnuExtSparseHeader.html\" title=\"struct tar::GnuExtSparseHeader\">GnuExtSparseHeader</a>","synthetic":false,"types":["tar::header::GnuExtSparseHeader"]}];
implementors["zip"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"zip/struct.DateTime.html\" title=\"struct zip::DateTime\">DateTime</a>","synthetic":false,"types":["zip::types::DateTime"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"zip/write/struct.FileOptions.html\" title=\"struct zip::write::FileOptions\">FileOptions</a>","synthetic":false,"types":["zip::write::FileOptions"]}];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()